Prefix: '&6&lBrowser&f&lMC'
Motd: '&7         &7&m--&8&l]&6&m-------&7   &6&lBrowser&f&lMC   &6&m-------&8&l[&7&m--&7                           &6&l&k||&7
  &7&nVenha treinar seu PvP&7 &6&l&k||'
Formulario: '&cEm Breve'
Loja: '&cEm Breve'
Twitter: '&cEm Breve'
TeamSpeak: '&cEm Breve'
